(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const views={
 overview:{label:'Briefing',kicker:'THIS WEEK',title:'Your AI search briefing',subtitle:'Three signals deserve your attention.',foot:'Answers are sampled repeatedly; coverage is directional.',menu:[['✦','For you','3'],['◫','All signals','12'],['↗','Changes','4'],'divider','Priority',['○','High impact','3'],['○','Needs review','2']]},
 answers:{label:'Questions',kicker:'VISIBILITY',title:'Buyer questions',subtitle:'See where your brand appears, and where it disappears.',foot:'Sampled answers are observations, not private conversation data.',menu:[['⌘','All questions','32'],['◎','ChatGPT','12'],['✳','Claude','10'],['◈','Perplexity','10'],'divider','Intent',['○','Commercial','14'],['○','Comparison','8'],['○','Integration','6']]},
 competitors:{label:'Competitors',kicker:'MARKET',title:'Competitive visibility',subtitle:'Understand who earns the answer and in which themes.',foot:'Coverage compares the same question set, engines and run schedule.',menu:[['⌘','All competitors','4'],['A','Acme','43%'],['L','Linear','72%'],['✓','Asana','65%'],'divider','Themes',['○','Integrations','8'],['○','Small teams','7'],['○','Pricing','5']]},
 opportunities:{label:'Actions',kicker:'NEXT MOVE',title:'Recommended action',subtitle:'Turn an evidence gap into a measurable experiment.',foot:'A shipped change starts a follow-up measurement window.',menu:[['✦','Recommended','3'],['○','Planned','2'],['✓','Shipped','7'],'divider','Impact',['○','High','3'],['○','Medium','4'],['○','Low','2']]},
 results:{label:'Results',kicker:'OUTCOMES',title:'AI-influenced demand',subtitle:'Connect identifiable referrals to business results.',foot:'Attribution includes only identifiable sessions and connected events.',menu:[['↗','Overview'],['◎','Referrals','1.2k'],['✓','Conversions','32'],'divider','Channel',['○','ChatGPT','18'],['○','Perplexity','9'],['○','Claude','4']]},
 visits:{label:'Sources',kicker:'DATA SOURCES',title:'Access and connections',subtitle:'Know which signal comes from where.',foot:'Crawls, sampled answers and human referrals are separate signals.',menu:[['⌘','All sources','4'],['☁','Cloudflare','Live'],['↗','Analytics','Live'],['G','Search Console','Live'],['＋','CRM','Setup'],'divider','Access',['○','Crawlers','12.8k'],['○','Human referrals','1.2k']]}
};
function animate(el){if(el&&!reduced.matches)el.animate([{opacity:.35,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'cubic-bezier(.22,1,.36,1)'});}
function contextMarkup(items){return items.map((item,i)=>item==='divider'?'<div class="context-divider"></div>':typeof item==='string'?`<span class="context-label">${item}</span>`:`<button class="${i===0?'active':''}"><span>${item[0]}</span><span>${item[1]}</span>${item[2]?`<small>${item[2]}</small>`:''}</button>`).join('');}
function setView(name,focus=false){const data=views[name]||views.overview;$$('[data-tab]').forEach(button=>{const active=button.dataset.tab===name;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;if(active&&focus)button.focus();});$$('.workspace-panel').forEach(panel=>panel.hidden=panel.id!==`panel-${name}`);$('#context-title').textContent=data.label;$('#context-menu').innerHTML=contextMarkup(data.menu);$('#breadcrumb-view').textContent=data.label;$('#workspace-kicker').textContent=data.kicker;$('#workspace-title').textContent=data.title;$('#workspace-subtitle').textContent=data.subtitle;$('#workspace-footnote').textContent=data.foot;$('.ds-select').hidden=name==='opportunities'||name==='visits';animate($(`#panel-${name}`));}
$$('[data-tab]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.tab)));
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>{setView(button.dataset.view);if(button.hasAttribute('data-scroll-product'))$('#product').scrollIntoView({block:'start',behavior:reduced.matches?'auto':'smooth'});}));
$('.workspace-tabs')?.addEventListener('keydown',e=>{const tabs=$$('.workspace-tabs [data-tab]'),i=tabs.indexOf(document.activeElement);if(i<0||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+tabs.length)%tabs.length;setView(tabs[next].dataset.tab,true);});
$('#context-menu')?.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;$$('#context-menu button').forEach(b=>b.classList.toggle('active',b===button));animate($('.workspace-panel:not([hidden])'));});
const dateTrigger=$('#date-trigger'),dateMenu=$('#date-menu'),options=$$('[data-period]');
function closeMenu(focus=false){if(!dateMenu)return;dateMenu.hidden=true;dateTrigger.setAttribute('aria-expanded','false');if(focus)dateTrigger.focus();}
function placeMenu(){if(!dateMenu||dateMenu.hidden)return;const r=dateTrigger.getBoundingClientRect(),w=Math.max(150,r.width);dateMenu.style.width=w+'px';dateMenu.style.left=Math.max(8,Math.min(r.right-w,innerWidth-w-8))+'px';dateMenu.style.top=(r.bottom+dateMenu.offsetHeight+8>innerHeight?r.top-dateMenu.offsetHeight-6:r.bottom+6)+'px';}
dateTrigger?.addEventListener('click',()=>{dateMenu.hidden=!dateMenu.hidden;dateTrigger.setAttribute('aria-expanded',String(!dateMenu.hidden));placeMenu();if(!dateMenu.hidden)options.find(o=>o.getAttribute('aria-selected')==='true')?.focus();});
options.forEach(option=>option.addEventListener('click',()=>{$('#date-label').textContent=option.textContent.trim();options.forEach(o=>o.setAttribute('aria-selected',String(o===option)));closeMenu(true);animate($('.workspace-panel:not([hidden])'));}));
dateMenu?.addEventListener('keydown',e=>{const i=options.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();options[e.key==='Home'?0:e.key==='End'?options.length-1:(i+(e.key==='ArrowDown'?1:-1)+options.length)%options.length].focus();}if(e.key==='Escape'){e.preventDefault();closeMenu(true);}});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.ds-select'))closeMenu();});window.addEventListener('resize',placeMenu);
const questions=[
 {question:'What’s the best project tool for a small design team?',answer:'For a small design team, Acme is worth a look. It brings projects, feedback, and your favorite tools together in one place.',source:'acme.so · Sample citation',status:'Your brand appears',explanation:'Your small-team positioning is coming through. Keep the supporting evidence fresh.'},
 {question:'Which project tools work with Figma and Slack?',answer:'Linear and Asana document their integration coverage clearly. Acme is not included in this sampled answer.',source:'linear.app · asana.com',status:'A gap to explore',explanation:'Your integrations page lacks the compatibility details cited in competitor answers.'},
 {question:'Compare Acme, Linear and Asana for agencies',answer:'Acme is a flexible choice for small creative teams, while Linear leads on product development and Asana on cross-functional planning.',source:'acme.so/compare · Sample citation',status:'Your brand is cited #2',explanation:'Your comparison page is helping. Add agency proof points to strengthen the recommendation.'}
];
$$('[data-question]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.question),d=questions[i];$$('[data-question]').forEach(b=>b.classList.toggle('active',b===button));$('#answer-question').textContent=d.question;$('#answer-text').textContent=d.answer;$('#answer-source').textContent=d.source;$('#answer-status').textContent=d.status;$('#answer-status').className='badge '+(i===1?'amber-badge':'green-badge');$('#answer-explanation').textContent=d.explanation;animate($('.sample-answer'));}));
function complete(done){$('#complete-example').hidden=done;$('#completion-state').hidden=!done;$('#opportunity-status').textContent=done?'Shipped · Monitoring':'Recommended · High impact';$('#opportunity-status').className='badge '+(done?'green-badge':'purple-badge');(done?$('#reset-example'):$('#complete-example')).focus();}
$('#complete-example')?.addEventListener('click',()=>complete(true));$('#reset-example')?.addEventListener('click',()=>complete(false));
$('.map-replay')?.addEventListener('click',()=>{const path=$('.signal-path');if(path&&!reduced.matches){const length=path.getTotalLength();path.animate([{strokeDasharray:length,strokeDashoffset:length},{strokeDasharray:length,strokeDashoffset:0}],{duration:650,easing:'ease-out'});}});
if(!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){animate(entry.target);observer.unobserve(entry.target);}}),{threshold:.15});observer.observe($('.workspace'));}
setView('overview');
})();
