(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let view='overview',period=30,metric='requests',pointIndex=0;
const model={
 requests:{label:'AI crawl requests',total:12846,previous:10831,base:[190,242,227,210,267,300,282,230,308,337,278,345,401,368,330,409,445,390,466,498,415,482,558,490,565,610,550,643,610,658]},
 referrals:{label:'AI-referred visits',total:1284,previous:1029,base:[20,23,29,24,33,25,31,37,30,34,38,42,32,39,35,42,46,39,41,48,44,50,54,48,55,62,58,65,69,72]},
 leads:{label:'Qualified leads',total:32,previous:24,base:[0,1,0,0,1,0,1,1,0,1,1,0,1,0,1,2,1,0,2,1,2,1,1,2,1,2,1,2,2,3]}
};
function scale(array,total){const sum=array.reduce((a,b)=>a+b,0), result=array.map(n=>Math.round(n/sum*total));let diff=total-result.reduce((a,b)=>a+b,0);let i=result.length-1;while(diff){const step=Math.sign(diff);if(result[i]+step>=0){result[i]+=step;diff-=step;}i=(i-1+result.length)%result.length;}return result;}
Object.values(model).forEach(m=>{m.series=scale(m.base,m.total);m.previousSeries=scale(m.base.map((n,i)=>Math.max(0,n*(.88+Math.sin(i*1.3)*.13))),m.previous);});
const titles={overview:['Your AI overview','See where you stand. Find your next move.'],visits:['Meet your AI visitors','See the pages AI services are reading.'],answers:['Your place in the answer','Explore the questions that matter to your buyers.'],opportunities:['A clear next move','Useful improvements, grounded in evidence.']};
function animate(element,frames,options={}){if(!reduced.matches)element.animate(frames,{duration:240,easing:'cubic-bezier(.22,1,.36,1)',...options});}
function setView(name,focus=false){view=name;$$('[data-tab]').forEach(button=>{const active=button.dataset.tab===name;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;if(active&&focus)button.focus();});$$('.workspace-panel').forEach(panel=>panel.hidden=panel.id!=='panel-'+name);$('#workspace-title').textContent=titles[name][0];$('#workspace-subtitle').textContent=titles[name][1];$('#breadcrumb-view').textContent=name==='visits'?'AI visits':name[0].toUpperCase()+name.slice(1);$('.ds-select').hidden=name==='answers'||name==='opportunities';$('#workspace-footnote').textContent=name==='answers'?'Illustrative answers, not live results from an AI provider.':name==='opportunities'?'A change is an experiment. Visibility is never guaranteed.':'Crawls, mentions, and human visits are separate signals.';closeMenu();animate($('#panel-'+name),[{opacity:.4,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}]);}
$$('[data-tab]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.tab)));
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>{setView(button.dataset.view);if(button.hasAttribute('data-show-leads')){metric='leads';renderChart(true);}if(button.hasAttribute('data-scroll-product'))$('#product').scrollIntoView({block:'start',behavior:reduced.matches?'instant':'smooth'});}));
$('.workspace-tabs').addEventListener('keydown',e=>{const tabs=$$('[data-tab]'),i=tabs.indexOf(document.activeElement);if(i<0||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+tabs.length)%tabs.length;setView(tabs[next].dataset.tab,true);});
function totalFor(key){return model[key].series.slice(-period).reduce((a,b)=>a+b,0);}
function renderChart(motion=false){
 $$('[data-metric]').forEach(button=>{const key=button.dataset.metric,m=model[key],n=totalFor(key);button.setAttribute('aria-pressed',String(key===metric));$('#stat-'+key).textContent=n.toLocaleString();const prev=m.previousSeries.slice(-period).reduce((a,b)=>a+b,0);button.querySelector('small>span').textContent=key==='leads'?`↑ ${n-prev}`:`↑ ${((n/prev-1)*100).toFixed(1)}%`;});
 const m=model[metric],values=m.series.slice(-period),previous=m.previousSeries.slice(-period);const max=Math.max(...values,...previous);const magnitude=metric==='leads'?1:max<100?10:100;const axis=Math.ceil(max/(magnitude*4))*magnitude*4;$('#chart-name').textContent=m.label;
 const path=a=>a.map((n,i)=>`${i?'L':'M'}${(i/(a.length-1)*760).toFixed(2)},${(165-n/axis*160).toFixed(2)}`).join(' ');const d=path(values);$('#chart-line').setAttribute('d',d);$('#chart-previous').setAttribute('d',path(previous));$('#chart-area-fill').setAttribute('d',d+'L760 165L0 165Z');$('#chart-y').innerHTML=[1,.75,.5,.25,0].map(n=>`<span>${axis*n}</span>`).join('');$('#chart-x').innerHTML=(period===30?['Aug 12','Aug 19','Aug 26','Sep 2','Sep 10']:['Sep 4','Sep 6','Sep 8','Sep 10']).map(s=>`<span>${s}</span>`).join('');$('#chart').setAttribute('aria-label',`${m.label}: ${totalFor(metric).toLocaleString()} over ${period} days. Illustrative data.`);
 const requests=totalFor('requests'),sourceCounts=scale([.5,.25,.16,.09],requests);['openai','claude','perplexity','other'].forEach((name,i)=>$('#source-'+name).textContent=sourceCounts[i].toLocaleString());hidePoint();
 if(motion){const length=$('#chart-line').getTotalLength();animate($('#chart-line'),[{strokeDasharray:length,strokeDashoffset:length},{strokeDasharray:length,strokeDashoffset:0}]);animate($('#chart-area-fill'),[{opacity:.2},{opacity:1}]);$$('.stats strong').forEach(el=>animate(el,[{transform:'translateY(4px)',opacity:.4},{transform:'translateY(0)',opacity:1}]));}
}
$$('[data-metric]').forEach(button=>button.addEventListener('click',()=>{metric=button.dataset.metric;renderChart(true);}));
const dateTrigger=$('#date-trigger'),dateMenu=$('#date-menu'),options=$$('[data-period]');
function closeMenu(restore=false){dateMenu.hidden=true;dateTrigger.setAttribute('aria-expanded','false');if(restore)dateTrigger.focus();}
function placeMenu(){if(dateMenu.hidden)return;const r=dateTrigger.getBoundingClientRect();const width=Math.min(Math.max(180,r.width),innerWidth-16);dateMenu.style.width=width+'px';dateMenu.style.left=Math.max(8,Math.min(r.right-width,innerWidth-width-8))+'px';const height=dateMenu.offsetHeight;dateMenu.style.top=(r.bottom+height+10>innerHeight?Math.max(8,r.top-height-6):r.bottom+6)+'px';}
function openMenu(){dateMenu.hidden=false;dateTrigger.setAttribute('aria-expanded','true');placeMenu();options.find(o=>Number(o.dataset.period)===period).focus();}
dateTrigger.addEventListener('click',()=>dateMenu.hidden?openMenu():closeMenu(true));dateTrigger.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();openMenu();}});
options.forEach(option=>option.addEventListener('click',()=>{period=Number(option.dataset.period);$('#date-label').textContent='Last '+period+' days';options.forEach(o=>o.setAttribute('aria-selected',String(Number(o.dataset.period)===period)));renderChart(true);closeMenu(true);}));
dateMenu.addEventListener('keydown',e=>{const i=options.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();options[e.key==='Home'?0:e.key==='End'?options.length-1:(i+(e.key==='ArrowDown'?1:-1)+options.length)%options.length].focus();}if(e.key==='Escape'){e.preventDefault();closeMenu(true);}if(e.key==='Tab')closeMenu(true);});document.addEventListener('pointerdown',e=>{if(!e.target.closest('.ds-select'))closeMenu();});window.addEventListener('scroll',placeMenu,true);window.addEventListener('resize',()=>{placeMenu();$('.workspace-tabs').setAttribute('aria-orientation',innerWidth<=740?'horizontal':'vertical');});$('.workspace-tabs').setAttribute('aria-orientation',innerWidth<=740?'horizontal':'vertical');
function hidePoint(){$('#chart-tooltip').hidden=true;$('#chart-cursor').setAttribute('hidden','');$('#chart-point').setAttribute('hidden','');}
function showPoint(index){const m=model[metric],values=m.series.slice(-period),previous=m.previousSeries.slice(-period),max=Math.max(...values,...previous),magnitude=metric==='leads'?1:max<100?10:100,axis=Math.ceil(max/(magnitude*4))*magnitude*4;pointIndex=Math.max(0,Math.min(values.length-1,index));const x=pointIndex/(values.length-1)*760,y=165-values[pointIndex]/axis*160;$('#chart-cursor').removeAttribute('hidden');$('#chart-cursor').setAttribute('x1',x);$('#chart-cursor').setAttribute('x2',x);$('#chart-point').removeAttribute('hidden');$('#chart-point').setAttribute('cx',x);$('#chart-point').setAttribute('cy',y);const date=new Date(Date.UTC(2026,period===30?7:8,(period===30?12:4)+pointIndex)),label=date.toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});const tooltip=$('#chart-tooltip');tooltip.textContent=`${label} · ${values[pointIndex].toLocaleString()}`;tooltip.hidden=false;const r=$('#chart').getBoundingClientRect(),relative=r.left-$('.chart-area').getBoundingClientRect().left+x/760*r.width;tooltip.style.left=Math.max(0,Math.min(relative-tooltip.offsetWidth/2,$('.chart-area').clientWidth-tooltip.offsetWidth))+'px';$('.chart-area').setAttribute('aria-label',`${m.label}. ${label}: ${values[pointIndex]}. Use left and right arrows to explore.`);}
$('#chart').addEventListener('pointermove',e=>{const r=$('#chart').getBoundingClientRect();showPoint(Math.round((e.clientX-r.left)/r.width*(period-1)));});$('.chart-area').addEventListener('pointerleave',hidePoint);$('.chart-area').addEventListener('blur',hidePoint);$('.chart-area').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End','Escape'].includes(e.key))return;e.preventDefault();if(e.key==='Escape')hidePoint();else showPoint(e.key==='Home'?0:e.key==='End'?period-1:pointIndex+(e.key==='ArrowRight'?1:-1));});
const questions=[{question:'What’s a good project tool for a small design team?',answer:'For a small design team, Acme is worth a look. It brings projects, feedback, and your favorite tools together in one place.',source:'acme.so · Sample citation',status:'Your brand appears',explanation:'Your small-team positioning is coming through. Keep your product facts and supporting examples fresh.'},{question:'Which project tools work with Figma and Slack?',answer:'Several project tools connect design feedback to your team’s workflow. Compare native integrations, setup requirements, and what each connection supports.',source:'Comparison guide · Sample citation',status:'A gap to explore',explanation:'Acme is missing from this example. Its integrations page lacks the compatibility details cited in competitor answers.'},{question:'What should I compare before choosing Acme?',answer:'Compare Acme on team size, integrations, and pricing. Its product pages are a useful starting point for checking which features fit your workflow.',source:'acme.so/compare · Sample citation',status:'Your brand appears',explanation:'Your comparison page is part of the answer. Review the product and pricing information so buyers find current details.'}];
$$('[data-question]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.question),data=questions[i];$$('[data-question]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#answer-question').textContent=data.question;$('#answer-text').textContent=data.answer;$('#answer-source').textContent=data.source;$('#answer-status').textContent=data.status;$('#answer-status').className='badge '+(i===1?'amber-badge':'green-badge');$('#answer-explanation').textContent=data.explanation;animate($('.answer-copy'),[{opacity:.3,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}]);}));
function completeExample(done){$('#complete-example').hidden=done;$('#completion-state').hidden=!done;$('#opportunity-status').textContent=done?'Sample update recorded':'A useful place to start';$('#opportunity-status').className='badge '+(done?'green-badge':'purple-badge');(done?$('#reset-example'):$('#complete-example')).focus();if(done)animate($('#completion-state'),[{opacity:.4,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}]);}
$('#complete-example').addEventListener('click',()=>completeExample(true));$('#reset-example').addEventListener('click',()=>completeExample(false));
$('.map-replay').addEventListener('click',()=>{const path=$('.signal-path'),length=path.getTotalLength();animate(path,[{strokeDasharray:length,strokeDashoffset:length},{strokeDasharray:length,strokeDashoffset:0}],{duration:650});animate($('.map-center'),[{boxShadow:'0 0 0 0 #918df633'},{boxShadow:'0 0 0 18px #918df600'}],{duration:650});});

renderChart();
if(!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;observer.unobserve(entry.target);if(entry.target.classList.contains('workspace')){animate(entry.target,[{opacity:.5,transform:'translateY(14px)'},{opacity:1,transform:'translateY(0)'}],{duration:550});}else{animate(entry.target,[{opacity:.5,transform:'translateY(7px) rotate(0)'},{opacity:1,transform:'translateY(0) rotate(-1.5deg)'}],{duration:400});}}),{threshold:.15});observer.observe($('.workspace'));observer.observe($('.outcome-visual'));}
})();
